repos:
- repo: local
  hooks:
  - id: nixpkgs-fmt
    name: nixpkgs-fmt
    description: Format nix code with nixpkgs-fmt.
    entry: nixpkgs-fmt
    language: system
    files: \.nix$
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v13.0.0
  hooks:
  - id: clang-format
    exclude: (?x)(
        ^hook/json.hpp$|
        ^hook/appdata|
        ^hook/frida-gum-devkit
      )
- repo: https://github.com/editorconfig-checker/editorconfig-checker.python
  rev: 2.3.54
  hooks:
  - id: editorconfig-checker
    alias: ec
    exclude: (?x)(
        ^.*\.cpp$|
        ^.*\.h$|
        ^.*\.hpp$
      )
