["github.com/BurntSushi/toml"]
  sumVersion = "v0.3.1"
  ["github.com/BurntSushi/toml".fetch]
    type = "git"
    url = "https://github.com/BurntSushi/toml"
    rev = "3012a1dbe2e4bd1391d42b32f0577cb7bbc7f005"
    sha256 = "1fjdwwfzyzllgiwydknf1pwjvy49qxfsczqx5gz3y0izs7as99j6"

["github.com/alecthomas/kong"]
  sumVersion = "v0.2.18"
  ["github.com/alecthomas/kong".fetch]
    type = "git"
    url = "https://github.com/alecthomas/kong"
    rev = "2770a34ce6d4b41741a2fc65ca666868f1c55fa2"
    sha256 = "01liy0az1rxkzan70k5mpcx9s2q7vqabcgkvfyzpwv4kba3n7qh3"

["github.com/davecgh/go-spew"]
  sumVersion = "v1.1.1"
  ["github.com/davecgh/go-spew".fetch]
    type = "git"
    url = "https://github.com/davecgh/go-spew"
    rev = "8991bc29aa16c548c550c7ff78260e27b9ab7c73"
    sha256 = "0hka6hmyvp701adzag2g26cxdj47g21x6jz4sc6jjz1mn59d474y"

["github.com/go-stack/stack"]
  sumVersion = "v1.8.0"
  ["github.com/go-stack/stack".fetch]
    type = "git"
    url = "https://github.com/go-stack/stack"
    rev = "2fee6af1a9795aafbe0253a0cfbdf668e1fb8a9a"
    sha256 = "0wk25751ryyvxclyp8jdk5c3ar0cmfr8lrjb66qbg4808x66b96v"

["github.com/gobuffalo/attrs"]
  sumVersion = "v0.0.0-20190224210810-a9411de4debd"
  ["github.com/gobuffalo/attrs".fetch]
    type = "git"
    url = "https://github.com/gobuffalo/attrs"
    rev = "a9411de4debdfe11f5ed58945ca2cd4f1c9b6539"
    sha256 = "11las2p8dcnhfnyj1jinxbjfcda9vpx6580v1q18dnfpnliyf23f"

["github.com/gobuffalo/depgen"]
  sumVersion = "v0.1.0"
  ["github.com/gobuffalo/depgen".fetch]
    type = "git"
    url = "https://github.com/gobuffalo/depgen"
    rev = "b051eb9db0827f4ced91ef9ef14bee3c9b6da6e8"
    sha256 = "1cd2ik5m1ffbppm2mk49nvfkbr8xwzl4n1cbz6vrybgy7a8m2ay8"

["github.com/gobuffalo/envy"]
  sumVersion = "v1.7.0"
  ["github.com/gobuffalo/envy".fetch]
    type = "git"
    url = "https://github.com/gobuffalo/envy"
    rev = "043cb4b8af871b49563291e32c66bb84378a60ac"
    sha256 = "03jarnkaf42xgfamb0jlya4c1cyk8gnxhcd21m3fx145vz4px398"

["github.com/gobuffalo/flect"]
  sumVersion = "v0.1.3"
  ["github.com/gobuffalo/flect".fetch]
    type = "git"
    url = "https://github.com/gobuffalo/flect"
    rev = "7b54dde751c39a3f05221667375657eff2acb230"
    sha256 = "13mwx7g1kgxmlfp4v76nafhzc2jgchagpc9pniwv7miq10y2frdk"

["github.com/gobuffalo/genny"]
  sumVersion = "v0.1.1"
  ["github.com/gobuffalo/genny".fetch]
    type = "git"
    url = "https://github.com/gobuffalo/genny"
    rev = "05dc5921e98daa5d406f90c2844ff163cb1e1c4e"
    sha256 = "03xkbzphpf80w6cywrs80vjgydalal5s3535krri0q074ylndpwb"

["github.com/gobuffalo/gitgen"]
  sumVersion = "v0.0.0-20190315122116-cc086187d211"
  ["github.com/gobuffalo/gitgen".fetch]
    type = "git"
    url = "https://github.com/gobuffalo/gitgen"
    rev = "cc086187d211fecdba9b9a657509e7d4252f4fc6"
    sha256 = "06wxipncn7576nq0n78h8mgcgmsahrxwazjzxx0mlc93sqsxikdx"

["github.com/gobuffalo/gogen"]
  sumVersion = "v0.1.1"
  ["github.com/gobuffalo/gogen".fetch]
    type = "git"
    url = "https://github.com/gobuffalo/gogen"
    rev = "5482e6ef5d999f8cfa9b038a53953c9b4ee090af"
    sha256 = "0z7i6bpjnw83d5y06bjpdkj8fijfpm1f4wq0pnzvi48n09wxy58z"

["github.com/gobuffalo/logger"]
  sumVersion = "v0.0.0-20190315122211-86e12af44bc2"
  ["github.com/gobuffalo/logger".fetch]
    type = "git"
    url = "https://github.com/gobuffalo/logger"
    rev = "86e12af44bc273e0063fad5b6ad588890b8cfe6b"
    sha256 = "0scxbkn30khqsmawmrfjagfki13pwnlycfg9j21dwi4xrz3lp5jb"

["github.com/gobuffalo/mapi"]
  sumVersion = "v1.0.2"
  ["github.com/gobuffalo/mapi".fetch]
    type = "git"
    url = "https://github.com/gobuffalo/mapi"
    rev = "0bb5e840be332d4280e40f2e6c50777c615bbac5"
    sha256 = "04mgk6caimkkv27wad3cmdsz055rrjl7j4cglsdv7xcmjkmxa4hw"

["github.com/gobuffalo/packd"]
  sumVersion = "v0.1.0"
  ["github.com/gobuffalo/packd".fetch]
    type = "git"
    url = "https://github.com/gobuffalo/packd"
    rev = "9efbb667f2024a9370cadda45a57a0657c88a6fb"
    sha256 = "03jgf710j1wf3195vv4vxf018zf02bhfkmnxmkl4nh34ancf86am"

["github.com/gobuffalo/packr/v2"]
  sumVersion = "v2.2.0"
  relPath = "v2"
  ["github.com/gobuffalo/packr/v2".fetch]
    type = "git"
    url = "https://github.com/gobuffalo/packr"
    rev = "cda4ac25577350dac682c8715dc6659327232596"
    sha256 = "0xir3f7cvplknz8yxydkxd6xxj2bv927kjmph9gpjkwff7gwgghn"

["github.com/gobuffalo/syncx"]
  sumVersion = "v0.0.0-20190224160051-33c29581e754"
  ["github.com/gobuffalo/syncx".fetch]
    type = "git"
    url = "https://github.com/gobuffalo/syncx"
    rev = "33c29581e754bd354236e977dfe426e55331c45d"
    sha256 = "1cxggm38vfwgrq6v3kv4cic24v60x9682p50dwxykc7995v76kd6"

["github.com/golang/snappy"]
  sumVersion = "v0.0.1"
  ["github.com/golang/snappy".fetch]
    type = "git"
    url = "https://github.com/golang/snappy"
    rev = "2a8bb927dd31d8daada140a5d09578521ce5c36a"
    sha256 = "0gp3kkzlm3wh37kgkhbqxq3zx07iqbgis5w9mf4d64h6vjq760is"

["github.com/google/go-cmp"]
  sumVersion = "v0.5.2"
  ["github.com/google/go-cmp".fetch]
    type = "git"
    url = "https://github.com/google/go-cmp"
    rev = "d2fcc899bdc2d134b7c00e36137260db963e193c"
    sha256 = "0qchy411jm9q2l9mf7x3ry2ycaqp9xdhf2nx14qrpzcxfigv2705"

["github.com/inconshreveable/mousetrap"]
  sumVersion = "v1.0.0"
  ["github.com/inconshreveable/mousetrap".fetch]
    type = "git"
    url = "https://github.com/inconshreveable/mousetrap"
    rev = "76626ae9c91c4f2a10f34cad8ce83ea42c93bb75"
    sha256 = "1mn0kg48xkd74brf48qf5hzp0bc6g8cf5a77w895rl3qnlpfw152"

["github.com/joho/godotenv"]
  sumVersion = "v1.3.0"
  ["github.com/joho/godotenv".fetch]
    type = "git"
    url = "https://github.com/joho/godotenv"
    rev = "23d116af351c84513e1946b527c88823e476be13"
    sha256 = "0ri8if0pc3x6jg4c3i8wr58xyfpxkwmcjk3rp8gb398a1aa3gpjm"

["github.com/karrick/godirwalk"]
  sumVersion = "v1.10.3"
  ["github.com/karrick/godirwalk".fetch]
    type = "git"
    url = "https://github.com/karrick/godirwalk"
    rev = "5e617d9cfec6f870e63b168e9a2fb7c490a1c108"
    sha256 = "00aspblilc8jhd2k3mah02jwq9q8fs6w3hx23ii0mihsl44qkq38"

["github.com/klauspost/compress"]
  sumVersion = "v1.13.6"
  ["github.com/klauspost/compress".fetch]
    type = "git"
    url = "https://github.com/klauspost/compress"
    rev = "38d4ba985ac157cb858763e016645e14e74c13c4"
    sha256 = "1bgqhv2pp56b8f5mfzpfjlm4cb262gjbqbp3235blhj9xf2wrynj"

["github.com/konsorten/go-windows-terminal-sequences"]
  sumVersion = "v1.0.2"
  ["github.com/konsorten/go-windows-terminal-sequences".fetch]
    type = "git"
    url = "https://github.com/konsorten/go-windows-terminal-sequences"
    rev = "f55edac94c9bbba5d6182a4be46d86a2c9b5b50e"
    sha256 = "09mn209ika7ciy87xf2x31dq5fnqw39jidgaljvmqxwk7ff1hnx7"

["github.com/kr/pretty"]
  sumVersion = "v0.1.0"
  ["github.com/kr/pretty".fetch]
    type = "git"
    url = "https://github.com/kr/pretty"
    rev = "73f6ac0b30a98e433b289500d779f50c1a6f0712"
    sha256 = "18m4pwg2abd0j9cn5v3k2ksk9ig4vlwxmlw9rrglanziv9l967qp"

["github.com/kr/pty"]
  sumVersion = "v1.1.1"
  ["github.com/kr/pty".fetch]
    type = "git"
    url = "https://github.com/kr/pty"
    rev = "282ce0e5322c82529687d609ee670fac7c7d917c"
    sha256 = "0383f0mb9kqjvncqrfpidsf8y6ns5zlrc91c6a74xpyxjwvzl2y6"

["github.com/kr/text"]
  sumVersion = "v0.1.0"
  ["github.com/kr/text".fetch]
    type = "git"
    url = "https://github.com/kr/text"
    rev = "e2ffdb16a802fe2bb95e2e35ff34f0e53aeef34f"
    sha256 = "1gm5bsl01apvc84bw06hasawyqm4q84vx1pm32wr9jnd7a8vjgj1"

["github.com/markbates/oncer"]
  sumVersion = "v0.0.0-20181203154359-bf2de49a0be2"
  ["github.com/markbates/oncer".fetch]
    type = "git"
    url = "https://github.com/markbates/oncer"
    rev = "bf2de49a0be218916e69a11d22866e6cd0a560f2"
    sha256 = "0rsxcfd166rysni6fsas40fjl3g17gbd3v6krpvm5rxq7ixcri9d"

["github.com/markbates/safe"]
  sumVersion = "v1.0.1"
  ["github.com/markbates/safe".fetch]
    type = "git"
    url = "https://github.com/markbates/safe"
    rev = "6fea05a5732486546a4836b7a1d596c5ec687b98"
    sha256 = "0kvhbyyf2gz0gkhql8qz5x9w366q73z55ayy3czj84iqhif2s2kh"

["github.com/mergermarket/go-pkcs7"]
  sumVersion = "v0.0.0-20170926155232-153b18ea13c9"
  ["github.com/mergermarket/go-pkcs7".fetch]
    type = "git"
    url = "https://github.com/mergermarket/go-pkcs7"
    rev = "153b18ea13c9b94f698070cadb23701e51a55b3e"
    sha256 = "08calgcgxvcymw8knzmzf0cf423xyg7g6n5l6fwd4gpg1gxp8mig"

["github.com/montanaflynn/stats"]
  sumVersion = "v0.0.0-20171201202039-1bf9dbcd8cbe"
  ["github.com/montanaflynn/stats".fetch]
    type = "git"
    url = "https://github.com/montanaflynn/stats"
    rev = "1bf9dbcd8cbe1fdb75add3785b1d4a9a646269ab"
    sha256 = "0qnx3hvd3lhwnmxg7nr4nwl5kbsc7ffnjk9ifyk0f05h61l3v9pz"

["github.com/pelletier/go-toml"]
  sumVersion = "v1.7.0"
  ["github.com/pelletier/go-toml".fetch]
    type = "git"
    url = "https://github.com/pelletier/go-toml"
    rev = "8e8d2a6aad23fcaa64716c5fa6975ec3abbf8281"
    sha256 = "0sqrwldjj2qxrgjz1diw1ffviya4ma7mz7nhdgydbisi2h55lqla"

["github.com/pkg/errors"]
  sumVersion = "v0.9.1"
  ["github.com/pkg/errors".fetch]
    type = "git"
    url = "https://github.com/pkg/errors"
    rev = "614d223910a179a466c1767a985424175c39b465"
    sha256 = "1761pybhc2kqr6v5fm8faj08x9bql8427yqg6vnfv6nhrasx1mwq"

["github.com/pmezard/go-difflib"]
  sumVersion = "v1.0.0"
  ["github.com/pmezard/go-difflib".fetch]
    type = "git"
    url = "https://github.com/pmezard/go-difflib"
    rev = "792786c7400a136282c1664665ae0a8db921c6c2"
    sha256 = "0c1cn55m4rypmscgf0rrb88pn58j3ysvc2d0432dp3c6fqg6cnzw"

["github.com/rogpeppe/go-internal"]
  sumVersion = "v1.3.0"
  ["github.com/rogpeppe/go-internal".fetch]
    type = "git"
    url = "https://github.com/rogpeppe/go-internal"
    rev = "438578804ca6f31be148c27683afc419ce47c06e"
    sha256 = "0mcdh1licgnnahwml9y2iq6xy5x9xmjw5frcnds2s3wpjyqrl216"

["github.com/sirupsen/logrus"]
  sumVersion = "v1.4.2"
  ["github.com/sirupsen/logrus".fetch]
    type = "git"
    url = "https://github.com/sirupsen/logrus"
    rev = "839c75faf7f98a33d445d181f3018b5c3409a45e"
    sha256 = "087k2lxrr9p9dh68yw71d05h5g9p5v26zbwd6j7lghinjfaw334x"

["github.com/speps/go-hashids/v2"]
  sumVersion = "v2.0.1"
  ["github.com/speps/go-hashids/v2".fetch]
    type = "git"
    url = "https://github.com/speps/go-hashids"
    rev = "24211a2d76b414d60682b8d02aecd981a4805ee0"
    sha256 = "0ck7p2maaw1jpyhlp6wqaf80wz8pzbhl59nzqn5f39magp0qjxhg"

["github.com/spf13/cobra"]
  sumVersion = "v0.0.3"
  ["github.com/spf13/cobra".fetch]
    type = "git"
    url = "https://github.com/spf13/cobra"
    rev = "ef82de70bb3f60c65fb8eebacbb2d122ef517385"
    sha256 = "1q1nsx05svyv9fv3fy6xv6gs9ffimkyzsfm49flvl3wnvf1ncrkd"

["github.com/spf13/pflag"]
  sumVersion = "v1.0.3"
  ["github.com/spf13/pflag".fetch]
    type = "git"
    url = "https://github.com/spf13/pflag"
    rev = "298182f68c66c05229eb03ac171abe6e309ee79a"
    sha256 = "1cj3cjm7d3zk0mf1xdybh0jywkbbw7a6yr3y22x9sis31scprswd"

["github.com/stretchr/objx"]
  sumVersion = "v0.1.1"
  ["github.com/stretchr/objx".fetch]
    type = "git"
    url = "https://github.com/stretchr/objx"
    rev = "477a77ecc69700c7cdeb1fa9e129548e1c1c393c"
    sha256 = "0iph0qmpyqg4kwv8jsx6a56a7hhqq8swrazv40ycxk9rzr0s8yls"

["github.com/stretchr/testify"]
  sumVersion = "v1.7.0"
  ["github.com/stretchr/testify".fetch]
    type = "git"
    url = "https://github.com/stretchr/testify"
    rev = "acba37e5db06f0093b465a7d47822bf13644b66c"
    sha256 = "0ixgjsvafr3513pz3r6pmgk074s2dxkll0dadvl25gkf30rkmh10"

["github.com/tidwall/pretty"]
  sumVersion = "v1.0.0"
  ["github.com/tidwall/pretty".fetch]
    type = "git"
    url = "https://github.com/tidwall/pretty"
    rev = "1166b9ac2b65e46a43d8618d30d1554f4652d49b"
    sha256 = "1jwpj5903lh8hsj9apm2gwd70809zq0gjgmivkxaq4iq29wnv0n9"

["github.com/xdg-go/pbkdf2"]
  sumVersion = "v1.0.0"
  ["github.com/xdg-go/pbkdf2".fetch]
    type = "git"
    url = "https://github.com/xdg-go/pbkdf2"
    rev = "7f452ef1dac88350356f1bb84a23748205e64b96"
    sha256 = "1nipijy5xkdnfyhkp5ryrjzm14si1i2v2xyfmblf84binwkbr8jh"

["github.com/xdg-go/scram"]
  sumVersion = "v1.0.2"
  ["github.com/xdg-go/scram".fetch]
    type = "git"
    url = "https://github.com/xdg-go/scram"
    rev = "2ad501880a7f7bcc9af290278baa3658c9a2f2cd"
    sha256 = "1jyv4qgc1dgh3v96pazmgljpp9ij25k8hwn0v4fck18g16i0nccm"

["github.com/xdg-go/stringprep"]
  sumVersion = "v1.0.2"
  ["github.com/xdg-go/stringprep".fetch]
    type = "git"
    url = "https://github.com/xdg-go/stringprep"
    rev = "4fcaaf19bc2a8e388ba275a82eb34c29abcd0bc9"
    sha256 = "1df0l5n3c520y9filzz83j42wa5c056jcygmfwhjyf1pq8f6jkv9"

["github.com/youmark/pkcs8"]
  sumVersion = "v0.0.0-20181117223130-1be2e3e5546d"
  ["github.com/youmark/pkcs8".fetch]
    type = "git"
    url = "https://github.com/youmark/pkcs8"
    rev = "1be2e3e5546da8a58903ff4adcfab015022538ea"
    sha256 = "0g20ydzhxrcrnm4azvgd1013cns7qiwsz1469w9mr2rwy4h2g8qn"

["go.mongodb.org/mongo-driver"]
  sumVersion = "v1.7.4"
  ["go.mongodb.org/mongo-driver".fetch]
    type = "git"
    url = "https://github.com/mongodb/mongo-go-driver.git"
    rev = "ddf065f0488ad1f1e61867a1ebd225e180f8f694"
    sha256 = "104y13px7yakd439697npm806v2kjgzwl8da84cmbz7kjrxpn8bn"

["golang.org/x/crypto"]
  sumVersion = "v0.0.0-20200302210943-78000ba7a073"
  ["golang.org/x/crypto".fetch]
    type = "git"
    url = "https://go.googlesource.com/crypto"
    rev = "78000ba7a073cafc0278790f6bce552a0f25850e"
    sha256 = "1rfwmd06x7qd276iw8h5sx06vggp4i4x40n7chbgs6qrn2zbcw8l"

["golang.org/x/net"]
  sumVersion = "v0.0.0-20190404232315-eb5bcb51f2a3"
  ["golang.org/x/net".fetch]
    type = "git"
    url = "https://go.googlesource.com/net"
    rev = "eb5bcb51f2a31c7d5141d810b70815c05d9c9146"
    sha256 = "17k4g8krxbl84gzcs275b7gsh66dzm15fdxivjnx9xz8q84l4kby"

["golang.org/x/sync"]
  sumVersion = "v0.0.0-20190911185100-cd5d95a43a6e"
  ["golang.org/x/sync".fetch]
    type = "git"
    url = "https://go.googlesource.com/sync"
    rev = "cd5d95a43a6e21273425c7ae415d3df9ea832eeb"
    sha256 = "1nqkyz2y1qvqcma52ijh02s8aiqmkfb95j08f6zcjhbga3ds6hds"

["golang.org/x/sys"]
  sumVersion = "v0.0.0-20190531175056-4c3a928424d2"
  ["golang.org/x/sys".fetch]
    type = "git"
    url = "https://go.googlesource.com/sys"
    rev = "4c3a928424d249a1013e789cf5e458d480bcba16"
    sha256 = "0hrr9jvlzvsqvmwlgbcgp1ffg44ns42z70a3lrl2j5cs42kwjvzl"

["golang.org/x/text"]
  sumVersion = "v0.3.5"
  ["golang.org/x/text".fetch]
    type = "git"
    url = "https://go.googlesource.com/text"
    rev = "75a595aef632b07c6eeaaa805adb6f0f66e4130e"
    sha256 = "082s9d7wnh1aa2v08g3h5z4if2f8hl4y01pb788qsvab9329lj0w"

["golang.org/x/tools"]
  sumVersion = "v0.0.0-20190531172133-b3315ee88b7d"
  ["golang.org/x/tools".fetch]
    type = "git"
    url = "https://go.googlesource.com/tools"
    rev = "b3315ee88b7da2b23cc6c62484a006958910e841"
    sha256 = "1lxhjhjz0jf6s8f8zjnr2y1m9l0fjhji9li55hlxxwb16pm7gznw"

["golang.org/x/xerrors"]
  sumVersion = "v0.0.0-20191204190536-9bdfabe68543"
  ["golang.org/x/xerrors".fetch]
    type = "git"
    url = "https://go.googlesource.com/xerrors"
    rev = "9bdfabe68543c54f90421aeb9a60ef8061b5b544"
    sha256 = "1yjfi1bk9xb81lqn85nnm13zz725wazvrx3b50hx19qmwg7a4b0c"

["gopkg.in/check.v1"]
  sumVersion = "v1.0.0-20180628173108-788fd7840127"
  ["gopkg.in/check.v1".fetch]
    type = "git"
    url = "https://gopkg.in/check.v1"
    rev = "788fd78401277ebd861206a03c884797c6ec5541"
    sha256 = "0v3bim0j375z81zrpr5qv42knqs0y2qv2vkjiqi5axvb78slki1a"

["gopkg.in/errgo.v2"]
  sumVersion = "v2.1.0"
  ["gopkg.in/errgo.v2".fetch]
    type = "git"
    url = "https://gopkg.in/errgo.v2"
    rev = "f768c5ab0476c50e978b039312180859c10fe8c0"
    sha256 = "065mbihiy7q67wnql0bzl9y1kkvck5ivra68254zbih52jxwrgr2"

["gopkg.in/yaml.v2"]
  sumVersion = "v2.2.8"
  ["gopkg.in/yaml.v2".fetch]
    type = "git"
    url = "https://gopkg.in/yaml.v2"
    rev = "53403b58ad1b561927d19068c655246f2db79d48"
    sha256 = "1inf7svydzscwv9fcjd2rm61a4xjk6jkswknybmns2n58shimapw"

["gopkg.in/yaml.v3"]
  sumVersion = "v3.0.0-20210107192922-496545a6307b"
  ["gopkg.in/yaml.v3".fetch]
    type = "git"
    url = "https://gopkg.in/yaml.v3"
    rev = "496545a6307b2a7d7a710fd516e5e16e8ab62dbc"
    sha256 = "06f4lnrp494wqaygv09dggr2dwf3z2bawqhnlnnwiamg5y787k4g"
